channels:
 - anaconda
 - conda-forge
dependencies:
 - tensorflow-gpu=2.4.1
 - biopython=1.78
 - tqdm=4.65.0
 - numpy=1.21
 - scikit-learn=1.3.0
 - matplotlib-base=3.8.0
 - pandas=1.5.3
 - scipy=1.7.3
 - jq=1.6
 - pip
 - pip:
   - keras==2.3.1
   - keras-bert==0.89.0
